version: 0.2

phases:
  install:
    runtime-version:
      java: corretto17
  build:
    commands:
      - echo Building, Testing and Packaging the application...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build, Testing and Packaging completed
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'